name: ferma
description: Planting app with AI

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_html: ^1.3.0
  flutter_local_notifications: ^5.0.0+1
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  get: ^4.1.3
  image_picker: ^0.7.4
  intl: ^0.17.0
  logger: ^1.0.0
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1

# To set up config file, run: `flutter pub run flutter_launcher_icons:main -f pubspec.yaml`
# To update the icon run: `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  remove_alpha_ios: true #to remove alpha channel on ios due to app store restriction

# To update the splashscreen run: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  image: "assets/images/splash_screen.png"
  color: "#3EA552"
  android_disable_fullscreen: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec  
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
